### ISSUE TITLE
Add ability to use proxy server

### ISSUE THREAD

**Issue by WenceyWang** [JackB1ack/telegram-notification#1]
It's know that telegram have been block in some area and the way to access Telegram Bot API is use a http(s) or sock5 proxy server.
I think it is necessary to add a option to config to use a proxy to access Telegram Bot API.

**Comment by JackB1ack** [comment]
Great, thanks for pointing this out! Telegram is actually blocked in my country too, but since I'm using mostly VSTS Hosted Agents this doesn't affect me. Anyway worth adding, will work on it.

**Comment by JackB1ack** [comment]
@WenceyWang  The feature is finally here! Since now on proxy support is on board. Make sure to update the extension and check it out! 

Readme updates are coming shortly. 
If you see any issues please report.
